### PR TITLE
Tech Features Upgraded!

### PR DESCRIPTION
**Pull request by Prid13**
The long-awaited upgrade is finally here! :)

# [LIVE DEMO](https://wgtwo-dev.netlify.app/technology/)

> image
----
> image

## Setup
- The primary file for all the features is **`src/features.sidebar.js`**. It holds _all_ the features as shown under the `/technology` page, in the order listed in the file (reordering can be done here). The file is divided into different Categories, each with a list of Features, which again include:
   - `name`: Name / Title of the Feature (will be shown in the Features list)
   - `href`: Link to the page with the Feature Details (all these files are located under `src/pages/technology/features`)
   - `tooltipText`: Text that will be shown when hovering over a feature under the `/technology` page
- As for the actual content, all Markdown files are located under `src/pages/technology/features` in their category folders.
   - Simply add a new `.md` file and write the content in there, making sure you include the frontmatter value `techFeaturePage: true`
   - The _name_ of the file needs to correspond to the `href` value in the `features.sidebar.js` file

## Editing / Adding Features
1. Go to `src/pages/technology/features` and navigate to the desired Category folder
2. Create a new `.md` file with a short name (no spaces, only dashes)
3. Include `techFeaturePage: true` in the frontmatter (see other files for reference)
4. Write the actual content in Markdown
5. Open `src/features.sidebar.js` file
6. Locate your Category, and insert a new item where the `name` is the name that will appear in the `/technology` page under the Features lists, the `href` needs to be the same as the file's name (e.g. `/my-new-file`, without `.md` suffix), and `tooltipText` is the text that will appear in the `/technology` page when hovering over that item. The order is also important, as it is the same as the file

## Notes
- It's a bit of a hacky solution bc I ended up resorting to Custom Docs pages for better control over the presentation and the future implementation ideas like the shopping cart one. It might be buggy, it might not be responsive, it might break when updating Docusarus, and the code looks really messy, but it works :)
- Tags are NOT clickable. Too much work to make them work properly. What's the intended effect when clicking on them?
- For the Custom Docs pages I've "swizzled" the MDXPage internal Docusaurus component, which I've also done for the "Case Study Redesign" PR, so there will be a merge conflict with these two PRs later on some time

### Improvement suggestions
- To avoid repeating info in the Features MDX pages (like title, slug, description), maybe try adding `remarkFrontmatter` plugin under `remarkPlugins` in docusaurus.config.js for gaining access to read the front matter

### CODE REVIEW

**Comment by torotimes** [comment]
WOOOW very cool! We're having a look at this now!

**Comment by Prid13** [comment]
@mtl-wgtwo next time, just unset the `devpages` label, and re-set it to trigger the deployment ;)

image

**Comment by torotimes** [comment]
Great! Got it for next time!

Did you have a look at those "meta images"? they're still too big.

**Review by jonny-wg2 — APPROVED** [review]
I love the implementation, design work is great, easy to understand, scalable for future growth and development in this space. Amazing work @Prid13 👍🏻 ⚔️

**Comment by torotimes** [comment]
Hey @Prid13 

Can you help me get this one unconflicted so I can view it in Netlify before deploying, please?

**Comment by Prid13** [comment]
> Hey @Prid13
> 
> Can you help me get this one unconflicted so I can view it in Netlify before deploying, please?

Done 😉

**Comment by torotimes** [comment]
Konge. Takker!

**Comment by jonny-wg2** [comment]
@torotimes  I guess this one is good to go to be deployed?

**Comment by torotimes** [comment]
Hi @jonny-wg2 - in principle, yes. The challenge is that getting enough engineering eyeballs on both QAing the short texts and starting to develop the individual feature landing pages is non-trivial. 

There's a detailed discussion on this in the #team-solution-design-presales channel on Slack. 

The bottom line is that this overview requires engineering or PM attention, not just once, but over time. That's why I've been hesitating to merge the page, although the functionality is good to go.

**Pull request merged**
