### PR TITLE
Angle Brackets Check for Contact Forms

### PR DESCRIPTION
**Pull request by Prid13**
**Changes:**
- Added regex to check for < and >
- Refactored code a bit to better highlight the element containing the error

**Pages:**
- /contact
- /request-demo
- /technology

**Improvement suggestions:**
- Combine all the 3 forms into a single Component that can easily be edited/customized to avoid repeating the code

Screenshot_3774

### CODE REVIEW

**Comment by jonny-wg2** [comment]
Looks great! We also have a contact form on the /security page too

**Comment by torotimes** [comment]
Nice. Is this good to be merged now, @jonny-wg2 ?

**Comment by jonny-wg2** [comment]
Nope not yet, we also need to add the new code to the contact form on the /security page

**Comment by torotimes** [comment]
> Nope not yet, we also need to add the new code to the contact form on the /security page

Ok. @Prid13 will you have a look at that?

**Comment by Prid13** [comment]
> Looks great! We also have a contact form on the /security page too

Whoops, thanks. Fixed now ;)

**Review by torotimes — APPROVED** [review]

**Pull request merged**
