### PR TITLE
Navbar Language Switch

### PR DESCRIPTION
**Pull request by Prid13**
Opted for "English" (instead of "EN").

It's a dropdown :)

image

image

## Mobile

image

image

### CODE REVIEW

**Comment by jonny-wg2** [comment]
Any chance you can make this flag icons? I find that it's quite large and doesn't looks the best.

**Comment by Prid13** [comment]
> Any chance you can make this flag icons? I find that it's quite large and doesn't looks the best.

Sure, but what flag should I use for English language? I actually thought of this idea, but then I got stuck on whether the UK or the US flag would fit best 😅

Also, should I use emojis (🇬🇧 | 🇯🇵) (they show up as "GB" and "JP" on Windows) or actual icons?

**Comment by torotimes** [comment]
Hey both, why don't we just use the (🇬🇧 | 🇯🇵) flags for now and just deploy this? We can always amend later. 

Wanna make that edit, @Prid13, and issue the PR? 

I guess I kind of agree with Zain on the usability issues by selecting language automatically based on location.

**Comment by Prid13** [comment]
Done :) On Windows the flags won't show up:

image

But they will on mobile. Something like this:

Screenshot_9823

**Review by torotimes — APPROVED** [review]

**Pull request merged**
