### PR TITLE
Blog Layout Redesign

### PR DESCRIPTION
**Pull request by Prid13**
# [LIVE DEMO](https://wgtwo-dev.netlify.app/)

image

---

image

---

### TODO:
- **Mobile responsiveness**

### CODE REVIEW

**Review by jonny-wg2 — COMMENTED** [review]
Looks great! I think we just need to make the wgtwo.com/blog mobile friendly and then we are good to go to merge!

**Comment by torotimes** [comment]
> 

In full support! Let's do this

**Comment by Prid13** [comment]
Alright, fixed the mobile layout. Please check for bugs and see if everything's okay :)

https://wgtwo-dev.netlify.app/blog/

image

**Comment by jorunfa** [comment]
I'm still no designer, but nitpicking/suggesting anyways
image

Would this look cleaner if it all was left aligned on one line (minus the read more)?
image
vs
image

Maybe not that important, but mentioning it anyways apparently 🤷

**Comment by torotimes** [comment]
Good call(s), @jorunfa 

Let's align. 

I also wonder if we should drop the hashtags on the cards on /blog. It's just noise. 

Finally, I wonder if we can make the page an infinite scroll? Choosing "older entries" after only 9 items feel a little cumbersome. Alternatively, double the number of entries before you need to go to the next page. 

Zain, we need to fix up the images for the first 5-6 posts (to make the front page look good). Can you get in touch when you're up today?

**Comment by Prid13** [comment]
Sure, what resolution are we talking about? :) Is the card image's aspect ratio good enough, or do we need to perhaps make the card taller? Or would you like to fix some of the _images_ in the front page to better fit in those image boxes? :) Like so:

image

Like you mentioned, there needs to be a certain aspect ratio that the images need to be in for them to look good enough. Not too long, not too tall, but sort of "widescreen", with a little bit of extra space at the edges for mobile responsivity (when website width gets narrower, the images also get a bit narrower).

The bigger problem, however, is how to best automate this. Making every author do this manually would be time-consuming and take focus away from the actual content 😅 I'm thinking maybe use an online tool with pre-configured settings to auto-crop the image quickly, OR, use a Github Action to automatically "fix" certain images upon opening a PR. What do you think? :)

**Comment by torotimes** [comment]
> Sure, what resolution are we talking about? :) Is the card image's aspect ratio good enough, or do we need to perhaps make the card taller? Or would you like to fix some of the _images_ in the front page to better fit in those image boxes? :) Like so:
> 
> image
> 
> Like you mentioned, there needs to be a certain aspect ratio that the images need to be in for them to look good enough. Not too long, not too tall, but sort of "widescreen", with a little bit of extra space at the edges for mobile responsivity (when website width gets narrower, the images also get a bit narrower).
> 
> The bigger problem, however, is how to best automate this. Making every author do this manually would be time-consuming and take focus away from the actual content 😅 I'm thinking maybe use an online tool with pre-configured settings to auto-crop the image quickly, OR, use a Github Action to automatically "fix" certain images upon opening a PR. What do you think? :)

Right on the money! 

Can you make those edits with the aspect ratio for the existing images, and then we'll set up an online tool for future posts?

**Comment by Prid13** [comment]
Alright, fixes deployed to devsite: https://wgtwo-dev.netlify.app/blog/

_PR Build Website check is failing bc ckhiod.com is down atm_

**Comment by torotimes** [comment]
Thanks for your hard work on this. 

We're looking into the broken link (well, not broken link, but external site that is down). 

Looking forward to merging this one!

**Comment by torotimes** [comment]
Can you start looking at an online tool where we can always get the right aspect ratio for the images? 

We should add the links and the guide here, as a readme:

image

**Comment by Prid13** [comment]
> Can you start looking at an online tool where we can always get the right aspect ratio for the images?

After sifting through dozens of online tools, I couldn't find a single one that did the job right or _didn't_ require registration, have watermarks, or was super-friendly... :/

So I made my own tool 😅

### Thumbnail Generator: https://jsfiddle.net/qz1pegoa/1/

This is only to be used for those images that are **too long** or **too tall**, or **just logos**. Normal "realistic" photos shouldn't require this, but doesn't hurt to try.

#### Example video:

https://user-images.githubusercontent.com/27897747/219536586-7e2de614-895b-45bf-9156-106742e41e34.mp4

**Comment by jorunfa** [comment]
> So I made my own tool 😅

Nifty!

I was going to be a boring old man and say one take 15 minutes to learn how to do it in Figma, but this looks quite promising.

(for posterity here is the boring old man way, but I shared it with @torotimes once before, so I think maybe it fell quite flat on it's face)

https://user-images.githubusercontent.com/1413275/219592361-23737e72-6074-4ddc-8634-de286220b2b8.mov

**Review by torotimes — APPROVED** [review]

**Comment by jorunfa** [comment]
Another nitpick (on the nav buttons), maybe for another day, since this PR was merged ✌️

current:
image

suggestion:
image

**Comment by torotimes** [comment]
> Another nitpick (on the nav buttons), maybe for another day, since this PR was merged ✌️
> 
> current: image
> 
> suggestion: image

@Prid13 - feel free to execute this one.

**Comment by Prid13** [comment]
@torotimes Awesome, it's live 8D! 🎉🥳

I like that suggestion, definitely makes the nav buttons look cleaner. But what I liked about the humongously long nav buttons is that they're much easier to move to and click on. Shorter buttons require much more precision and "effort" to use, if that makes sense. Maybe I can make them smaller but have the "hit area" (the invisible clickable area) be larger? :)

**Comment by Prid13** [comment]
> (for posterity here is the boring old man way, but I shared it with @torotimes once before, so I think maybe it fell quite flat on it's face)

@jorunfa Wow, didn't see that till now -- great effort making that video and proposing the manual solution 👏 I greatly appreciate all your inputs and feedback, and your willingness to help and go out of your way to provide amazing things like that video and all those edited screenshots ⭐ God bless you with the best, for you are one talented individual, and I am looking forward to future collaborations 😇

**Pull request merged**
