### PR TITLE
Home text translated into Japanese.

### PR DESCRIPTION
**Pull request by apo2205**
Please confirm.

### CODE REVIEW

**Review by jonny-wg2 — APPROVED** [review]
👍🏻

**Comment by jonny-wg2** [comment]
You need to run `yarn prettier` to make the pr to pass https://github.com/working-group-two/wgtwo.com/actions/runs/3293664690/jobs/5437733996#step:4:20

**Comment by apo2205** [comment]
Thanks for the review. run prettier so please confirm!

**Review by Prid13 — APPROVED** [review]
Really great work! Love the effort put in. Otsukaresama 👏⭐

Btw, the preview test (where you can view your changes live at https://wgtwo-dev.netlify.app/) is failing because you do not have permission to make changes to this repository. If it's no big deal to preview the changes, just remove the `devpages` label :)

**Comment by jonny-wg2** [comment]
@apo2205 please except the github invitation to be a member of this repo and then you will have rights to run gh actions on prs 
image

**Pull request merged**
