### PR TITLE
[Demo] Victor alf - Devpages

### PR DESCRIPTION
**Pull request by Prid13**
For demonstration purposes.

https://wgtwo-dev.netlify.app/

https://wgtwo-dev.netlify.app/jp

### CODE REVIEW

**Comment by torotimes** [comment]
Hi @Prid13 

Can you take a stab at this one? 

I got a series of changes from my colleague Naoya in Japan. 

See the attached document for details. 

Feel free to reach out to me. 

Important clarification:
Don't add a new top menu item, but we need to make it visible from /jp front page, and add a link in the footer. 

[230307 Last Change.pptx](https://github.com/working-group-two/wgtwo.com/files/10978041/230307.Last.Change.pptx)

**Comment by Prid13** [comment]
Will do 😇

**Comment by torotimes** [comment]
Thanks, Zain. 

Can you give me a time estimate for the work? I mean, how soon you can have the edits done?

**Comment by Prid13** [comment]
How about by now? ;)

Everything's done, except having a link in the frontpage to the new page (the link is in the footer, though, as "Implementation" under Product).

The link can be placed anywhere in the frontpage and it will only show up in the japanese version. Where do they want it? 😇

**Comment by torotimes** [comment]
Hi Zain, here are the final edits. Can you apply those edits? After that, I think we should be good to go!

Thanks!


[230323 Last-Last Change.pptx](https://github.com/working-group-two/wgtwo.com/files/11048034/230323.Last-Last.Change.pptx)

**Comment by Prid13** [comment]
Check now :) https://wgtwo-dev.netlify.app/jp/implementation/

**Review by torotimes — APPROVED** [review]

**Comment by torotimes** [comment]
Thanks - I have merged it! Well done.

We'll probably need to add a link to this page from the /jp front page, so stay tuned for that. But I'll close this issue/PR now.

**Pull request merged**
