### PR TITLE
Don't index Dev site

### PR DESCRIPTION
**Pull request by Prid13**
@jonny-wg2 is it `build/robots.txt` or `website/build/robots.txt` in package.json? Haven't tested it, but hoping the former works 😅

### CODE REVIEW

**Comment by Prid13** [comment]
Whoops, maybe creating another PR from same branch wasn't such a good idea. Got all those old commits polluting this page 😅

**Comment by jonny-wg2** [comment]
Tested and it works as intenteded!  We already do a `cd website` before the build so that's why it works
image

Yeah you will need to rebase again from main. Feel free to make a new pr if easier though.

**Review by jonny-wg2 — APPROVED** [review]
👍🏻

**Comment by Prid13** [comment]
Working on a Sunday, eh? Rare, but respected sight 👏⭐

**Pull request merged**
