### PR TITLE
Update Language Switch CSS

### PR DESCRIPTION
**Pull request by Prid13**
Fixed the CSS somewhat. Have a look:

https://github.com/working-group-two/wgtwo.com/assets/27897747/a23d41f6-a6f4-4403-9f66-b428f02bfaa5

With Windows emojis:

Screenshot_191

### CODE REVIEW

**Review by torotimes — APPROVED** [review]

**Review by jonny-wg2 — APPROVED** [review]

**Comment by torotimes** [comment]
@jonny-wg2 can you help me resolve the prettier issue? 

😅

**Review by torotimes — APPROVED** [review]

**Comment by torotimes** [comment]
Hi @jonny-wg2 - can you help me with those 2 broken links? I can't figure out which 2 links are broken! 

😅

**Comment by torotimes** [comment]
Thanks, @Prid13. I have removed those two broken links now.

**Review by torotimes — APPROVED** [review]

**Comment by torotimes** [comment]
@Prid13, hmm, the check is still not successful. what did I mess up?

**Comment by Prid13** [comment]
@torotimes hmm, not sure, there was no specific error message. But there was another "broken" link: https://www.ecma-international.org/publications-and-standards/standards/ecma-404/

Found here: https://github.com/working-group-two/wgtwo.com/blob/feecacc751bb85934058ecad38cd6c4293096281/blog/2022-01-11-the-spec-behind-the-specs.md?plain=1#L1352

Maybe we should retry after disabling/removing that link? :)

**Comment by torotimes** [comment]
Thanks! I've removed that dead link now. Let's see

**Review by torotimes — APPROVED** [review]

**Comment by Prid13** [comment]
Good to go 😇✨

**Comment by torotimes** [comment]
yeaaaaaaaaaa! 

image

**Pull request merged**
